// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: proto/silicon.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 模型信息
type Model struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OwnedBy       string                 `protobuf:"bytes,2,opt,name=owned_by,json=ownedBy,proto3" json:"owned_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Model) Reset() {
	*x = Model{}
	mi := &file_proto_silicon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Model) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Model) ProtoMessage() {}

func (x *Model) ProtoReflect() protoreflect.Message {
	mi := &file_proto_silicon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Model.ProtoReflect.Descriptor instead.
func (*Model) Descriptor() ([]byte, []int) {
	return file_proto_silicon_proto_rawDescGZIP(), []int{0}
}

func (x *Model) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Model) GetOwnedBy() string {
	if x != nil {
		return x.OwnedBy
	}
	return ""
}

// 获取模型列表响应
type GetModelListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*Model               `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetModelListResponse) Reset() {
	*x = GetModelListResponse{}
	mi := &file_proto_silicon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetModelListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetModelListResponse) ProtoMessage() {}

func (x *GetModelListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_silicon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetModelListResponse.ProtoReflect.Descriptor instead.
func (*GetModelListResponse) Descriptor() ([]byte, []int) {
	return file_proto_silicon_proto_rawDescGZIP(), []int{1}
}

func (x *GetModelListResponse) GetData() []*Model {
	if x != nil {
		return x.Data
	}
	return nil
}

// 聊天消息
type ChatMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatMessage) Reset() {
	*x = ChatMessage{}
	mi := &file_proto_silicon_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatMessage) ProtoMessage() {}

func (x *ChatMessage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_silicon_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatMessage.ProtoReflect.Descriptor instead.
func (*ChatMessage) Descriptor() ([]byte, []int) {
	return file_proto_silicon_proto_rawDescGZIP(), []int{2}
}

func (x *ChatMessage) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ChatMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

// 响应格式
type ResponseFormat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseFormat) Reset() {
	*x = ResponseFormat{}
	mi := &file_proto_silicon_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseFormat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseFormat) ProtoMessage() {}

func (x *ResponseFormat) ProtoReflect() protoreflect.Message {
	mi := &file_proto_silicon_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseFormat.ProtoReflect.Descriptor instead.
func (*ResponseFormat) Descriptor() ([]byte, []int) {
	return file_proto_silicon_proto_rawDescGZIP(), []int{3}
}

func (x *ResponseFormat) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

// 函数对象
type FunctionObject struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Description   string                 `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Strict        bool                   `protobuf:"varint,3,opt,name=strict,proto3" json:"strict,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FunctionObject) Reset() {
	*x = FunctionObject{}
	mi := &file_proto_silicon_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FunctionObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionObject) ProtoMessage() {}

func (x *FunctionObject) ProtoReflect() protoreflect.Message {
	mi := &file_proto_silicon_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionObject.ProtoReflect.Descriptor instead.
func (*FunctionObject) Descriptor() ([]byte, []int) {
	return file_proto_silicon_proto_rawDescGZIP(), []int{4}
}

func (x *FunctionObject) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *FunctionObject) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FunctionObject) GetStrict() bool {
	if x != nil {
		return x.Strict
	}
	return false
}

// 工具
type Tool struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Function      *FunctionObject        `protobuf:"bytes,2,opt,name=function,proto3" json:"function,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Tool) Reset() {
	*x = Tool{}
	mi := &file_proto_silicon_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Tool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Tool) ProtoMessage() {}

func (x *Tool) ProtoReflect() protoreflect.Message {
	mi := &file_proto_silicon_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Tool.ProtoReflect.Descriptor instead.
func (*Tool) Descriptor() ([]byte, []int) {
	return file_proto_silicon_proto_rawDescGZIP(), []int{5}
}

func (x *Tool) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Tool) GetFunction() *FunctionObject {
	if x != nil {
		return x.Function
	}
	return nil
}

// 聊天请求
type ChatCompletionRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Model            string                 `protobuf:"bytes,1,opt,name=model,proto3" json:"model,omitempty"`
	Messages         []*ChatMessage         `protobuf:"bytes,2,rep,name=messages,proto3" json:"messages,omitempty"`
	Stream           bool                   `protobuf:"varint,3,opt,name=stream,proto3" json:"stream,omitempty"`
	MaxTokens        int32                  `protobuf:"varint,4,opt,name=max_tokens,json=maxTokens,proto3" json:"max_tokens,omitempty"`
	Stop             []string               `protobuf:"bytes,5,rep,name=stop,proto3" json:"stop,omitempty"`
	Temperature      float32                `protobuf:"fixed32,6,opt,name=temperature,proto3" json:"temperature,omitempty"`
	TopP             float32                `protobuf:"fixed32,7,opt,name=top_p,json=topP,proto3" json:"top_p,omitempty"`
	TopK             int32                  `protobuf:"varint,8,opt,name=top_k,json=topK,proto3" json:"top_k,omitempty"`
	FrequencyPenalty float32                `protobuf:"fixed32,9,opt,name=frequency_penalty,json=frequencyPenalty,proto3" json:"frequency_penalty,omitempty"`
	N                int32                  `protobuf:"varint,10,opt,name=n,proto3" json:"n,omitempty"`
	ResponseFormat   *ResponseFormat        `protobuf:"bytes,11,opt,name=response_format,json=responseFormat,proto3" json:"response_format,omitempty"`
	Tools            []*Tool                `protobuf:"bytes,12,rep,name=tools,proto3" json:"tools,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ChatCompletionRequest) Reset() {
	*x = ChatCompletionRequest{}
	mi := &file_proto_silicon_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatCompletionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatCompletionRequest) ProtoMessage() {}

func (x *ChatCompletionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_silicon_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatCompletionRequest.ProtoReflect.Descriptor instead.
func (*ChatCompletionRequest) Descriptor() ([]byte, []int) {
	return file_proto_silicon_proto_rawDescGZIP(), []int{6}
}

func (x *ChatCompletionRequest) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ChatCompletionRequest) GetMessages() []*ChatMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ChatCompletionRequest) GetStream() bool {
	if x != nil {
		return x.Stream
	}
	return false
}

func (x *ChatCompletionRequest) GetMaxTokens() int32 {
	if x != nil {
		return x.MaxTokens
	}
	return 0
}

func (x *ChatCompletionRequest) GetStop() []string {
	if x != nil {
		return x.Stop
	}
	return nil
}

func (x *ChatCompletionRequest) GetTemperature() float32 {
	if x != nil {
		return x.Temperature
	}
	return 0
}

func (x *ChatCompletionRequest) GetTopP() float32 {
	if x != nil {
		return x.TopP
	}
	return 0
}

func (x *ChatCompletionRequest) GetTopK() int32 {
	if x != nil {
		return x.TopK
	}
	return 0
}

func (x *ChatCompletionRequest) GetFrequencyPenalty() float32 {
	if x != nil {
		return x.FrequencyPenalty
	}
	return 0
}

func (x *ChatCompletionRequest) GetN() int32 {
	if x != nil {
		return x.N
	}
	return 0
}

func (x *ChatCompletionRequest) GetResponseFormat() *ResponseFormat {
	if x != nil {
		return x.ResponseFormat
	}
	return nil
}

func (x *ChatCompletionRequest) GetTools() []*Tool {
	if x != nil {
		return x.Tools
	}
	return nil
}

// 聊天响应中的选择
type Choice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       *ChatMessage           `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	Index         int32                  `protobuf:"varint,2,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Choice) Reset() {
	*x = Choice{}
	mi := &file_proto_silicon_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Choice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Choice) ProtoMessage() {}

func (x *Choice) ProtoReflect() protoreflect.Message {
	mi := &file_proto_silicon_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Choice.ProtoReflect.Descriptor instead.
func (*Choice) Descriptor() ([]byte, []int) {
	return file_proto_silicon_proto_rawDescGZIP(), []int{7}
}

func (x *Choice) GetMessage() *ChatMessage {
	if x != nil {
		return x.Message
	}
	return nil
}

func (x *Choice) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

// Token使用统计
type Usage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	PromptTokens     int32                  `protobuf:"varint,1,opt,name=prompt_tokens,json=promptTokens,proto3" json:"prompt_tokens,omitempty"`
	CompletionTokens int32                  `protobuf:"varint,2,opt,name=completion_tokens,json=completionTokens,proto3" json:"completion_tokens,omitempty"`
	TotalTokens      int32                  `protobuf:"varint,3,opt,name=total_tokens,json=totalTokens,proto3" json:"total_tokens,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Usage) Reset() {
	*x = Usage{}
	mi := &file_proto_silicon_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Usage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Usage) ProtoMessage() {}

func (x *Usage) ProtoReflect() protoreflect.Message {
	mi := &file_proto_silicon_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Usage.ProtoReflect.Descriptor instead.
func (*Usage) Descriptor() ([]byte, []int) {
	return file_proto_silicon_proto_rawDescGZIP(), []int{8}
}

func (x *Usage) GetPromptTokens() int32 {
	if x != nil {
		return x.PromptTokens
	}
	return 0
}

func (x *Usage) GetCompletionTokens() int32 {
	if x != nil {
		return x.CompletionTokens
	}
	return 0
}

func (x *Usage) GetTotalTokens() int32 {
	if x != nil {
		return x.TotalTokens
	}
	return 0
}

// 聊天响应
type ChatCompletionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Object        string                 `protobuf:"bytes,2,opt,name=object,proto3" json:"object,omitempty"`
	Created       int64                  `protobuf:"varint,3,opt,name=created,proto3" json:"created,omitempty"`
	Model         string                 `protobuf:"bytes,4,opt,name=model,proto3" json:"model,omitempty"`
	Choices       []*Choice              `protobuf:"bytes,5,rep,name=choices,proto3" json:"choices,omitempty"`
	Usage         *Usage                 `protobuf:"bytes,6,opt,name=usage,proto3" json:"usage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatCompletionResponse) Reset() {
	*x = ChatCompletionResponse{}
	mi := &file_proto_silicon_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatCompletionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatCompletionResponse) ProtoMessage() {}

func (x *ChatCompletionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_silicon_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatCompletionResponse.ProtoReflect.Descriptor instead.
func (*ChatCompletionResponse) Descriptor() ([]byte, []int) {
	return file_proto_silicon_proto_rawDescGZIP(), []int{9}
}

func (x *ChatCompletionResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChatCompletionResponse) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

func (x *ChatCompletionResponse) GetCreated() int64 {
	if x != nil {
		return x.Created
	}
	return 0
}

func (x *ChatCompletionResponse) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *ChatCompletionResponse) GetChoices() []*Choice {
	if x != nil {
		return x.Choices
	}
	return nil
}

func (x *ChatCompletionResponse) GetUsage() *Usage {
	if x != nil {
		return x.Usage
	}
	return nil
}

// 空消息
type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_silicon_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_silicon_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_silicon_proto_rawDescGZIP(), []int{10}
}

var File_proto_silicon_proto protoreflect.FileDescriptor

const file_proto_silicon_proto_rawDesc = "" +
	"\n" +
	"\x13proto/silicon.proto\x12\asilicon\"2\n" +
	"\x05Model\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\bowned_by\x18\x02 \x01(\tR\aownedBy\":\n" +
	"\x14GetModelListResponse\x12\"\n" +
	"\x04data\x18\x01 \x03(\v2\x0e.silicon.ModelR\x04data\";\n" +
	"\vChatMessage\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\"$\n" +
	"\x0eResponseFormat\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\"^\n" +
	"\x0eFunctionObject\x12 \n" +
	"\vdescription\x18\x01 \x01(\tR\vdescription\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06strict\x18\x03 \x01(\bR\x06strict\"O\n" +
	"\x04Tool\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x123\n" +
	"\bfunction\x18\x02 \x01(\v2\x17.silicon.FunctionObjectR\bfunction\"\x98\x03\n" +
	"\x15ChatCompletionRequest\x12\x14\n" +
	"\x05model\x18\x01 \x01(\tR\x05model\x120\n" +
	"\bmessages\x18\x02 \x03(\v2\x14.silicon.ChatMessageR\bmessages\x12\x16\n" +
	"\x06stream\x18\x03 \x01(\bR\x06stream\x12\x1d\n" +
	"\n" +
	"max_tokens\x18\x04 \x01(\x05R\tmaxTokens\x12\x12\n" +
	"\x04stop\x18\x05 \x03(\tR\x04stop\x12 \n" +
	"\vtemperature\x18\x06 \x01(\x02R\vtemperature\x12\x13\n" +
	"\x05top_p\x18\a \x01(\x02R\x04topP\x12\x13\n" +
	"\x05top_k\x18\b \x01(\x05R\x04topK\x12+\n" +
	"\x11frequency_penalty\x18\t \x01(\x02R\x10frequencyPenalty\x12\f\n" +
	"\x01n\x18\n" +
	" \x01(\x05R\x01n\x12@\n" +
	"\x0fresponse_format\x18\v \x01(\v2\x17.silicon.ResponseFormatR\x0eresponseFormat\x12#\n" +
	"\x05tools\x18\f \x03(\v2\r.silicon.ToolR\x05tools\"N\n" +
	"\x06Choice\x12.\n" +
	"\amessage\x18\x01 \x01(\v2\x14.silicon.ChatMessageR\amessage\x12\x14\n" +
	"\x05index\x18\x02 \x01(\x05R\x05index\"|\n" +
	"\x05Usage\x12#\n" +
	"\rprompt_tokens\x18\x01 \x01(\x05R\fpromptTokens\x12+\n" +
	"\x11completion_tokens\x18\x02 \x01(\x05R\x10completionTokens\x12!\n" +
	"\ftotal_tokens\x18\x03 \x01(\x05R\vtotalTokens\"\xc1\x01\n" +
	"\x16ChatCompletionResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x16\n" +
	"\x06object\x18\x02 \x01(\tR\x06object\x12\x18\n" +
	"\acreated\x18\x03 \x01(\x03R\acreated\x12\x14\n" +
	"\x05model\x18\x04 \x01(\tR\x05model\x12)\n" +
	"\achoices\x18\x05 \x03(\v2\x0f.silicon.ChoiceR\achoices\x12$\n" +
	"\x05usage\x18\x06 \x01(\v2\x0e.silicon.UsageR\x05usage\"\a\n" +
	"\x05Empty2\xac\x01\n" +
	"\x0eSiliconService\x12?\n" +
	"\fGetModelList\x12\x0e.silicon.Empty\x1a\x1d.silicon.GetModelListResponse\"\x00\x12Y\n" +
	"\x14CreateChatCompletion\x12\x1e.silicon.ChatCompletionRequest\x1a\x1f.silicon.ChatCompletionResponse\"\x00B%Z#github.com/kriswu/go_deepseek/protob\x06proto3"

var (
	file_proto_silicon_proto_rawDescOnce sync.Once
	file_proto_silicon_proto_rawDescData []byte
)

func file_proto_silicon_proto_rawDescGZIP() []byte {
	file_proto_silicon_proto_rawDescOnce.Do(func() {
		file_proto_silicon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_silicon_proto_rawDesc), len(file_proto_silicon_proto_rawDesc)))
	})
	return file_proto_silicon_proto_rawDescData
}

var file_proto_silicon_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_silicon_proto_goTypes = []any{
	(*Model)(nil),                  // 0: silicon.Model
	(*GetModelListResponse)(nil),   // 1: silicon.GetModelListResponse
	(*ChatMessage)(nil),            // 2: silicon.ChatMessage
	(*ResponseFormat)(nil),         // 3: silicon.ResponseFormat
	(*FunctionObject)(nil),         // 4: silicon.FunctionObject
	(*Tool)(nil),                   // 5: silicon.Tool
	(*ChatCompletionRequest)(nil),  // 6: silicon.ChatCompletionRequest
	(*Choice)(nil),                 // 7: silicon.Choice
	(*Usage)(nil),                  // 8: silicon.Usage
	(*ChatCompletionResponse)(nil), // 9: silicon.ChatCompletionResponse
	(*Empty)(nil),                  // 10: silicon.Empty
}
var file_proto_silicon_proto_depIdxs = []int32{
	0,  // 0: silicon.GetModelListResponse.data:type_name -> silicon.Model
	4,  // 1: silicon.Tool.function:type_name -> silicon.FunctionObject
	2,  // 2: silicon.ChatCompletionRequest.messages:type_name -> silicon.ChatMessage
	3,  // 3: silicon.ChatCompletionRequest.response_format:type_name -> silicon.ResponseFormat
	5,  // 4: silicon.ChatCompletionRequest.tools:type_name -> silicon.Tool
	2,  // 5: silicon.Choice.message:type_name -> silicon.ChatMessage
	7,  // 6: silicon.ChatCompletionResponse.choices:type_name -> silicon.Choice
	8,  // 7: silicon.ChatCompletionResponse.usage:type_name -> silicon.Usage
	10, // 8: silicon.SiliconService.GetModelList:input_type -> silicon.Empty
	6,  // 9: silicon.SiliconService.CreateChatCompletion:input_type -> silicon.ChatCompletionRequest
	1,  // 10: silicon.SiliconService.GetModelList:output_type -> silicon.GetModelListResponse
	9,  // 11: silicon.SiliconService.CreateChatCompletion:output_type -> silicon.ChatCompletionResponse
	10, // [10:12] is the sub-list for method output_type
	8,  // [8:10] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_proto_silicon_proto_init() }
func file_proto_silicon_proto_init() {
	if File_proto_silicon_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_silicon_proto_rawDesc), len(file_proto_silicon_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_silicon_proto_goTypes,
		DependencyIndexes: file_proto_silicon_proto_depIdxs,
		MessageInfos:      file_proto_silicon_proto_msgTypes,
	}.Build()
	File_proto_silicon_proto = out.File
	file_proto_silicon_proto_goTypes = nil
	file_proto_silicon_proto_depIdxs = nil
}
